global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kea-dhcp'
    static_configs:
      - targets: ['192.168.50.2:9600', '192.168.50.3:9600']

  - job_name: 'bind9'
    static_configs:
      - targets: ['192.168.50.2:9113', '192.168.50.3:9113']
